import { BuiltInCommandCategory } from "@/types/dashboard";

export const BUILTIN_COMMANDS: BuiltInCommandCategory[] = [
  {
    name: "Moderation",
    id: "Moderation",
    commands: [
      { name: "ban", description: "Permanently ban a user from the server.", adminOnly: true },
      { name: "unban", description: "Remove a ban from a user.", adminOnly: true },
      { name: "kick", description: "Remove a user from the server.", adminOnly: true },
      { name: "timeout", description: "Temporarily mute a user.", adminOnly: true },
      { name: "untimeout", description: "Remove a timeout from a user.", adminOnly: true },
      { name: "warn", description: "Issue a warning to a user.", adminOnly: true },
      { name: "warnings", description: "View a user's warning history.", adminOnly: true },
      { name: "clearwarnings", description: "Remove all warnings from a user.", adminOnly: true },
      { name: "userinfo", description: "Display user information.", adminOnly: true },
      { name: "membercount", description: "Show number of server members.", adminOnly: true },
      { name: "nickname", description: "Change a user's nickname.", adminOnly: true },
      { name: "resetnickname", description: "Reset a user's nickname.", adminOnly: true },
      { name: "servermute", description: "Mute a user in voice channels.", adminOnly: true },
      { name: "serverunmute", description: "Unmute a user in voice channels.", adminOnly: true },
      { name: "softban", description: "Ban and unban a user to clear messages.", adminOnly: true },
      { name: "massban", description: "Ban multiple users at once.", adminOnly: true },
    ],
  },
  {
    name: "Message / Channel Moderation",
    id: "MessageModeration",
    commands: [
      { name: "clear", description: "Delete a specified number of messages.", adminOnly: true },
      { name: "purge", description: "Bulk delete messages from a channel.", adminOnly: true },
      { name: "purgeuser", description: "Delete messages from a specific user.", adminOnly: true },
      { name: "purgebots", description: "Delete messages sent by bots.", adminOnly: true },
      { name: "purgelinks", description: "Delete messages containing links.", adminOnly: true },
      { name: "purgeattachments", description: "Delete messages containing attachments.", adminOnly: true },
      { name: "purgeembeds", description: "Delete messages containing embeds.", adminOnly: true },
      { name: "slowmode", description: "Set slowmode delay for the channel.", adminOnly: true },
      { name: "lock", description: "Lock a channel to prevent messages.", adminOnly: true },
      { name: "unlock", description: "Unlock a channel.", adminOnly: true },
      { name: "lockdown", description: "Lock all channels in the server.", adminOnly: true },
      { name: "unlockdown", description: "Unlock all channels in the server.", adminOnly: true },
      { name: "channelmute", description: "Mute a user in a specific channel.", adminOnly: true },
      { name: "channelunmute", description: "Unmute a user in a specific channel.", adminOnly: true },
      { name: "renamechannel", description: "Rename a channel.", adminOnly: true },
      { name: "slowmodeoff", description: "Disable slowmode for a channel.", adminOnly: true },
      { name: "hidechannel", description: "Hide a channel from members.", adminOnly: true },
      { name: "showchannel", description: "Show a channel to members.", adminOnly: true },
      { name: "logchannel", description: "Set the moderation log channel.", adminOnly: true },
    ],
  },
  {
    name: "Role Moderation",
    id: "RoleModeration",
    commands: [
      { name: "giverole", description: "Assign a role to a user.", adminOnly: true },
      { name: "removerole", description: "Remove a role from a user.", adminOnly: true },
      { name: "mute", description: "Mute a user using the configured mute role.", adminOnly: true },
      { name: "unmute", description: "Remove mute role from a user.", adminOnly: true },
      { name: "temprole", description: "Assign a role for a limited time.", adminOnly: true },
      { name: "rolelock", description: "Lock a user's current roles.", adminOnly: true },
      { name: "unrolelock", description: "Unlock a user's roles.", adminOnly: true },
      { name: "roleinfo", description: "Display information about a role." },
      { name: "autorole", description: "Set or disable automatic role for new members.", adminOnly: true },
      { name: "setmuterole", description: "Set the mute role for this server.", adminOnly: true },
    ],
  },
  {
    name: "Anti-Abuse / Safety",
    id: "AntiAbuse",
    commands: [
      { name: "antispam", description: "Enable or disable spam protection.", adminOnly: true },
      { name: "antilink", description: "Block or allow unauthorized links.", adminOnly: true },
      { name: "antiinvite", description: "Block or allow Discord invite links.", adminOnly: true },
      { name: "antiraid", description: "Enable or disable raid protection.", adminOnly: true },
      { name: "antiabusepolicy", description: "View or update anti-abuse escalation policy.", adminOnly: true },
      { name: "blacklist", description: "Add a user to the bot blacklist.", adminOnly: true },
      { name: "unblacklist", description: "Remove a user from the bot blacklist.", adminOnly: true },
    ],
  },
  {
    name: "General",
    id: "BotHelp",
    commands: [
      { name: "help", description: "Show all available slash commands and their descriptions." },
    ],
  },
];
